CinemaFriend/urls.py
from django.contrib import admin
from django.urls import path, include

from CinemaFriend import views

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),

    path('accounts/profile/<str:user_login>/', views.profile, name='profile'),

    path('accounts/register/', include('registration.urls')),

    path('', views.index, name='index'),
    path('rating/', views.rating, name='rating'),

    path('search/', views.search, name='search'),

    path('news/', include('news.urls')),
    path('movies/', include('movies.urls')),
    path('serials/', include('serials.urls')),
    path('contact/', include('contact.urls')),
]

apps/contact/urls.py
from django.urls import path

from . import views

app_name = 'contacts'
urlpatterns = [
    path('', views.index, name='index'),
    path('sended/', views.sended, name='sended'),
]

apps/movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/', views.detail, name='detail'),
]

apps/news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('<int:news_id>/', views.detail, name='detail'),
]

apps/serials/urls.py
from django.urls import path

from . import views

app_name = 'serials'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:serial_id>/', views.detail, name='detail'),
]

templates/index/main.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block menu %}

    <li class="active"><a href="{% url 'index' %}">Главная</a></li>
    <li><a href="{% url 'movies:index' %}">Фильмы</a></li>
    <li><a href="{% url 'serials:index' %}">Сериалы</a></li>
    <li><a href="{% url 'rating' %}">Рейтинг фильмов</a></li>
    <li><a href="{% url 'contacts:index' %}">Контакты</a></li>

{% endblock %}

{% block content %}

    {% if latest_movies_list %}

        <!-- Section title -->
        <h2>Новые фильмы</h2>
        <hr>

        <!-- Section row -->
        <div class="row">

            {% for m in latest_movies_list %}

                <!-- Film block -->
                <div class="film_block col-lg-3 col-md-3 col-sm-3 col-xs-6">

                    <!-- Link to content -->
                    <a href="{% url 'movies:detail' m.id %}">

                        <!-- Film poster -->
                        <img class="img-thumbnail" src="{{ m.movie_url_poster }}" alt="{{ m.movie_title }} Poster">
                    </a>

                    <!-- Link to content -->
                    <a href="{% url 'movies:detail' m.id %}">

                        <!-- Label block -->
                        <div class="film_label">

                            <!-- Film label -->
                            {{ m.movie_title }}

                            {% if m.was_pub_recently %}

                                <br>

                                <!-- Badge -->
                                <div class="badge">Новое!</div>

                            {% endif %}
                        </div>
                    </a>

                </div>

            {% endfor %}
        </div>

    {% else %}

        <!-- Empty message -->
        <h4>Наш программист ушел в отпуск и без него наши фильмы ушли, извините 🤷‍</h4>
        <hr>

    {% endif %}

    <!-- Divider -->
    <div class="margin-8"></div>

    {% if latest_serials_list %}

        <!-- Section title -->
        <h2>Новые сериалы</h2>
        <hr>

        <!-- Section row -->
        <div class="row">

            {% for s in latest_serials_list %}

                <!-- Serial block -->
                <div class="film_block col-lg-3 col-md-3 col-sm-3 col-xs-6">

                    <!-- Link to content -->
                    <a href="{% url 'serials:detail' s.id %}">

                        <!-- Serial poster -->
                        <img class="img-thumbnail" src="{{ s.serial_url_poster }}" alt="{ s.serial_title }} Poster">
                    </a>

                    <!-- Link to content -->
                    <a href="{% url 'serials:detail' s.id %}">

                        <!-- Label block -->
                        <div class="film_label">

                            <!-- Serial label -->
                            {{ s.serial_title }}

                            {% if s.was_pub_recently %}

                                <br>

                                <!-- Badge -->
                                <div class="badge">Новое!</div>

                            {% endif %}
                        </div>
                    </a>

                </div>

            {% endfor %}
        </div>

    {% else %}

        <!-- Empty message -->
        <h4>Наш программист ушел в отпуск и без него наши сериалы ушли, извините 🤷‍</h4>
        <hr>

    {% endif %}

    <!-- Divider -->
    <div class="margin-8"></div>

    {% if latest_news_list %}

        <!-- Section title -->
        <h2>Новости</h2>
        <hr>

        <!-- Content list -->
        <ul class="list-group">

            {% for n in latest_news_list %}

                <!-- List item -->
                <li class="list-group-item list-group-item-warning">

                    <!-- Item title -->
                    <h4>{{ n.news_title }}</h4>

                    <!-- Link to content -->
                    <a style="margin-top: -35px;" class="btn btn-warning pull-right"
                       href="{% url 'news:detail' n.id %}">Читать</a>
                </li>

            {% endfor %}
        </ul>

    {% else %}

        <!-- Empty message -->
        <h4>Наш программист ушел в отпуск и без него наши новости ушли, извините 🤷‍</h4>

    {% endif %}

{% endblock %}

templates/index/rating.html
{% extends 'base.html' %}

{% block title %}Рейтинг фильмов{% endblock %}

{% block menu %}

    <li><a href="{% url 'index' %}">Главная</a></li>
    <li><a href="{% url 'movies:index' %}">Фильмы</a></li>
    <li><a href="{% url 'serials:index' %}">Сериалы</a></li>
    <li class="active"><a href="{% url 'rating' %}">Рейтинг фильмов</a></li>
    <li><a href="{% url 'contacts:index' %}">Контакты</a></li>

{% endblock %}

{% block content %}

    {% if movies_list %}

        <!-- Page title -->
        <h1>Рейтинг фильмов:</h1>
        <hr>

        <!-- Rating table -->
        <table class="table table-bordered">

            <!-- Head -->
            <thead>

            <!-- Row -->
            <tr>
                <!-- Columns -->
                <th></th>
                <th>Фильм</th>
                <th class="text-center">Год</th>
                <th class="text-center">Рейтинг</th>
            </tr>
            </thead>

            <!-- Body -->
            <tbody>

            {% for m in movies_list %}

                <!-- Row -->
                <tr>

                    <!-- Poster column -->
                    <td class="col-lg-2 col-md-2 col-sm-2 col-xs-2">

                        <!-- Poster image -->
                        <img class="img-responsive img-thumbnail" src="{{ m.movie_url_poster }}"
                             alt="{{ m.movie_title }} Poster">
                    </td>

                    <!-- Title column -->
                    <td class="vert-align">

                        <!-- Link to content -->
                        <a href="{% url 'movies:detail' m.id %}">{{ m.movie_title }}</a>
                    </td>

                    <!-- Year column -->
                    <td class="text-center vert-align">{{ m.movie_year }}</td>

                    <!-- Rating column -->
                    <td class="text-center vert-align">

                        <!-- Badge -->
                        <span class="badge">{{ m.movie_rating }}</span>
                    </td>
                </tr>

            {% endfor %}
            </tbody>
        </table>

    {% else %}

        <!-- Empty message -->
        <h2>Фильмы не найдены...</h2>

    {% endif %}

    <!-- Deviner block -->
    <hr>

{% endblock %}