CinemaFriend/urls.py
from django.contrib import admin
from django.urls import path, include

from CinemaFriend import views

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),

    path('accounts/profile/<str:user_login>/', views.profile, name='profile'),

    path('accounts/register/', include('registration.urls')),

    path('', views.index, name='index'),
    path('rating/', views.rating, name='rating'),

    path('search/', views.search, name='search'),

    path('news/', include('news.urls')),
    path('movies/', include('movies.urls')),
    path('serials/', include('serials.urls')),
    path('contact/', include('contact.urls')),
]

apps/contact/urls.py
from django.urls import path

from . import views

app_name = 'contacts'
urlpatterns = [
    path('', views.index, name='index'),
    path('sended/', views.sended, name='sended'),
]

apps/movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/', views.detail, name='detail'),
]

apps/serials/urls.py
from django.urls import path

from . import views

app_name = 'serials'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:serial_id>/', views.detail, name='detail'),
]

apps/contact/models.py
from django.db import models


# Create your models here.

class Ticket(models.Model):
    ticket_name = models.CharField('Имя отправителя:', max_length=50)
    username_author = models.CharField('Имя пользователя отправителя:', max_length=60)
    ticket_email = models.CharField('Почта отправителя:', max_length=70)

    ticket_text = models.TextField('Сообщение отправителя:')

    def __str__(self):
        return self.ticket_name

    class Meta:
        verbose_name = 'Запрос'
        verbose_name_plural = 'Запросы'

apps/contact/views.py
from django.shortcuts import render

from .models import Ticket


# Create your views here.

def index(request):
    return render(request, 'contact/main.html')


def sended(request):
    ticket = Ticket(ticket_name=request.POST['author'], ticket_email=request.POST['email'],
                    ticket_text=request.POST['message'], username_author=request.POST['username_author'])
    ticket.save()

    return render(request, 'contact/sended.html')

templates/contact/main.html
{% extends 'base.html' %}

{% block title %}Контакты{% endblock %}

{% block menu %}

    <li><a href="{% url 'index' %}">Главная</a></li>
    <li><a href="{% url 'movies:index' %}">Фильмы</a></li>
    <li><a href="{% url 'serials:index' %}">Сериалы</a></li>
    <li><a href="{% url 'rating' %}">Рейтинг фильмов</a></li>
    <li class="active"><a href="{% url 'contacts:index' %}">Контакты</a></li>

{% endblock %}

{% block content %}

    <!-- Page title -->
    <h1>Контакты</h1>
    <hr>

    <!-- Description -->
    <p style="font-size: 18px; margin-bottom: 3%;">Здесь вы можете связаться с администратором нашего портала.</p>

    <!-- Send ticket form -->
    <form action="{% url 'contacts:sended' %}" method="POST">

        <!-- CSRF protection -->
        {% csrf_token %}

        <!-- Bootstrap form-group -->
        <div class="form-group">

            {% if user.is_authenticated %}

                <!-- Name field -->
                <input type="text" name="author" required class="form-control" placeholder="Ваше имя:"
                       value="{{ user.first_name }}">

                <!-- Username field -->
                <input type="hidden" name="username_author" value="{{ user.username }}">

            {% else %}

                <!-- Name field -->
                <input type="text" name="author" required class="form-control" placeholder="Ваше имя:">

                <!-- Username field -->
                <input type="hidden" name="username_author" value="Аноним">

            {% endif %}
        </div>

        <!-- Bootstrap form-group -->
        <div class="input-group form-group">

            {% if user.is_authenticated %}

                <!-- Email field -->
                <input type="email" name="email" required class="form-control" placeholder="Ваш Email:"
                       value="{{ user.email }}" autocomplete="off">

            {% else %}

                <!-- Email field -->
                <input type="email" name="email" required class="form-control" placeholder="Ваш Email:"
                       autocomplete="off">

            {% endif %}

            <!-- Input addon -->
            <span class="input-group-addon">@example.com</span>
        </div>

        <!-- Bootstrap form-group -->
        <div class="form-group">

            <!-- Message field -->
            <textarea required name="message" class="form-control" placeholder="Ваше сообщение:"
                      autocomplete="off"></textarea>
        </div>

        <!-- Send button -->
        <button type="submit" class="btn btn-lg btn-warning pull-right">Отправить</button>
    </form>

    <!-- Deviner block -->
    <hr>

{% endblock %}

templates/contact/sended.html
{% extends 'base.html' %}

{% block title %}Контакты{% endblock %}

{% block menu %}

    <li><a href="{% url 'index' %}">Главная</a></li>
    <li><a href="{% url 'movies:index' %}">Фильмы</a></li>
    <li><a href="{% url 'serials:index' %}">Сериалы</a></li>
    <li><a href="{% url 'rating' %}">Рейтинг фильмов</a></li>
    <li class="active"><a href="{% url 'contacts:index' %}">Контакты</a></li>

{% endblock %}

{% block content %}

    <!-- Page title -->
    <h1>Контакты</h1>
    <hr>

    <!-- Description -->
    <p style="font-size: 18px; margin-bottom: 3%;">Запрос отправлен, вам ответят по Email, удачи 😀</p>

    <!-- Reverse link -->
    <a class="btn btn-lg btn-warning" href="{% url 'contacts:index' %}">Вернуться</a>

    <!-- Deviner block -->
    <hr>

{% endblock %}